name: 'food_analytics'
version: '1.0.0'
config-version: 2

profile: 'food_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  food_analytics:
    # Config for models in the 'bronze' folder
    bronze:
      +materialized: view
      +schema: bronze
    
    # Config for models in the 'silver' folder
    silver:
      +materialized: table
      +schema: silver

    # Config for models in the 'gold' folder
    gold:
      +materialized: table
      +schema: gold
